# Generated by Django 4.2.7 on 2025-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_joboffer_options_joboffer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
