# Generated by Django 4.2.7 on 2025-05-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_joboffer_api_joboffe_salary__1dd5a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_modality', models.CharField(blank=True, max_length=50)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
