# Generated by Django 4.2.7 on 2025-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='modality',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['title', 'company'], name='api_joboffe_title_2bd3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['location', 'category'], name='api_joboffe_locatio_67fc22_idx'),
        ),
    ]
