# Generated by Django 4.2.7 on 2025-05-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_joboffer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='education_level',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='experience_years',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_max',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_min',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
