# Generated by Django 4.2.7 on 2025-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_joboffer_contract_type_joboffer_education_level_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['salary_min', 'salary_max'], name='api_joboffe_salary__1dd5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['experience_years', 'education_level'], name='api_joboffe_experie_f617eb_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['contract_type', 'modality'], name='api_joboffe_contrac_25610a_idx'),
        ),
    ]
